### ISSUE TITLE
Similarity ordering not working

### ISSUE THREAD

**Issue by benjbach** [networkcube/vistorian-matrix#10]

**Comment by jamesscottbrown** [comment]
This is a problem with module imports.

`vistorian-matrix` imports the `ordering.ts` file from `matrix-core`; this file imports the `reordering.js` library and uses the `optimal_leaf_order` function it provides.

When webpack builds `vistorian-matrix/lib/index.js`, it generates some new code:

```js
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "orderNodes", function() { return orderNodes; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "OrderingConfiguration", function() { return OrderingConfiguration; });
/* harmony import */ var reorder_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! reorder.js */ "../vistorian-core/node_modules/reorder.js/reorder.v1.js");
/* harmony import */ var reorder_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(reorder_js__WEBPACK_IMPORTED_MODULE_0__);
```

and replaces `reorder.optimal_leaf_order` with `reorder_js__WEBPACK_IMPORTED_MODULE_0__["optimal_leaf_order"]`.

This doesn't work, as `reorder_js__WEBPACK_IMPORTED_MODULE_0__` ends up empty, presumably because of the relative path ` "../vistorian-core/node_modules/reorder.js/reorder.v1.js"`.

I think the solution is to change the [`package.json` file](https://github.com/networkcube/vistorian-matrix/blob/master/package.json#L53) to specify a package version to load from NPM, rather than using `"vistorian-core": "file:../vistorian-core"`.
However, this requires a new release of `vistorian-core` to be published on npm, as there have been important changes since this was last done.

**Comment by benjbach** [comment]
I tried to deploy a new version of `vistorian-code` but it's having issues with the loader (presumabley `ts-loader`, through this is installed and declared in both `webpack` and `package.json`). I tried loading an earlier version of `vistorian-core` (eg. `0.0.2` but that has other issues and does not compile the code either. @jamesscottbrown, happy to chat later if you want ot have a look.

**Comment by jamesscottbrown** [comment]
This has been addressed in the version in the [`vistorian-monorepo`](https://github.com/networkcube/vistorian-monorepo) repository.
